name: Package Extension

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Package extension
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: stub  # Not needed for packaging only
          dryRun: true
          
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: doom-themes-extension
          path: "*.vsix" 